import type { Metadata } from "next";
import type { ReactNode } from "react";
import { cookies } from "next/headers";
import { AppProviders } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeStoreId = cookieStore.get("activeStoreId")?.value ?? null;

  return (
    <html lang="en">
      <body className="antialiased">
        <AppProviders initialActiveStoreId={activeStoreId}>{children}</AppProviders>
      </body>
    </html>
  );
}
