import type { Metadata } from "next";
import type { ReactNode } from "react";
import { cookies } from "next/headers";

import { DEFAULT_LOCALE, isLocale, type Locale } from "@/lib/i18n";
import { AppProviders } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeStoreId = cookieStore.get("activeStoreId")?.value ?? null;
  const localeCookie = cookieStore.get("locale")?.value ?? null;

  let locale: Locale = DEFAULT_LOCALE;
  if (localeCookie && isLocale(localeCookie)) {
    locale = localeCookie;
  } else {
    try {
      cookieStore.set("locale", DEFAULT_LOCALE, {
        path: "/",
        httpOnly: false,
        sameSite: "lax",
      });
    } catch {
      // ignore failures to persist locale cookie
    }
  }

  return (
    <html lang={locale}>
      <body className="antialiased">
        <AppProviders initialActiveStoreId={activeStoreId} initialLocale={locale}>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
