import type { Metadata } from "next";
import type { ReactNode } from "react";
import { cookies } from "next/headers";

import { DEFAULT_LOCALE, isLocale } from "@/lib/i18n";
import { AppProviders } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeStoreId = cookieStore.get("activeStoreId")?.value ?? null;
  const localeCookie = cookieStore.get("locale")?.value ?? null;
  const locale = isLocale(localeCookie) ? localeCookie : DEFAULT_LOCALE;

  return (
    <html lang={locale}>
      <body className="antialiased">
        <AppProviders initialActiveStoreId={activeStoreId} initialLocale={locale}>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
